
    charset utf-8;
 
    #location / {
        #try_files $uri $uri/ /index.php?$query_string;
        #try_files /page-cache/pc__index__pc.html /index.php?$query_string;  
    #}

    #location / {
        #try_files $uri $uri/ /page-cache/$uri.html /page-cache/$uri.json /page-cache/$uri.xml /index.php?$query_string;
    #}

    location ~ /get-category-data-by-symbol/.* {
        try_files $uri $uri/ /page-cache/$uri.html /page-cache/$uri.json /page-cache/$uri.xml /index.php?$query_string;
    }

    location = / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ /get-category-data-by-symbol/.* {
        try_files $uri $uri/ /page-cache/$uri.html /page-cache/$uri.json /page-cache/$uri.xml /index.php?$query_string;
    }

    #location ~ /category/.* {
    #    try_files $uri $uri/ /page-cache/$uri.html /page-cache/$uri.json /page-cache/$uri.xml /index.php?$query_string;
    #}

    location ~ /get-symbol-extra-info/.* {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ /get-advenced-rules-.* {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /validate-data/ {
        client_max_body_size 990M;
	proxy_read_timeout 7600s;
        fastcgi_read_timeout 7600s;
        proxy_send_timeout 7600s;
        fastcgi_send_timeout 7600s;
        fastcgi_connect_timeout 2400s;
    }

    location ~ /.* {
        try_files $uri $uri/ /index.php?$query_string;
        #try_files $uri $uri/ /page-cache/$uri.html /page-cache/$uri.json /page-cache/$uri.xml /index.php?$query_string;
        #try_files $uri $uri/ /page-cache/get-configurator/$1/pc__index__pc.html /index.php?$query_string; #pc__index__pc.html
    }
 
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
 
    error_page 404 /index.php;

    location ~ /\.(?!well-known).* {
        deny all;
    }


gzip on;
gzip_disable "msie6";

gzip_comp_level 6;
gzip_min_length 1100;
gzip_buffers 16 8k;
gzip_proxied any;
gzip_types
        text/plain
        text/css
        text/js
        text/xml
        text/javascript
        application/javascript
        application/x-javascript
        application/json
        application/xml
        application/xml+rss
        application/wasm
        application/font-woff
        application/octet-stream
        image/svg+xml;
gzip_vary on;